dbt_models:
  outputs:
    local_dev:
      database: AwsDataCatalog
      region_name: ap-southeast-2
      s3_data_dir: "s3://{{ env_var('PROCESSED_BUCKET_NAME') }}"
      s3_staging_dir: "s3://{{ env_var('ATHENA_RESULTS_BUCKET') }}"
      schema: "{{ env_var('GLUE_DATABASE_NAME') }}"
      threads: 1
      type: athena
      aws_profile_name: dev
    dev:
      database: AwsDataCatalog
      region_name: ap-southeast-2
      s3_data_dir: "s3://{{ env_var('PROCESSED_BUCKET_NAME') }}"
      s3_staging_dir: "s3://{{ env_var('ATHENA_RESULTS_BUCKET') }}"
      schema: "{{ env_var('GLUE_DATABASE_NAME') }}"
      threads: 1
      type: athena
  target: dev